spring:

  springdoc:
    version: 3.0

  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:~/superheros;MODE=MySQL
    username: sa
    password: 1234

  flyway:
    baseline-on-migrate: true
    clean-disabled: true
    url: jdbc:h2:mem:~/superheros;MODE=MySQL
    user: sa
    password: 1234

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none