version: '3'
services:
  flyway:
    image: flyway/flyway
    command: -url=jdbc:h2:mem://db -schemas=myschema -user=root -password=P@ssw0rd -connectRetries=60 migrate
    volumes:
      - .:/flyway/sql
    depends_on:
      - db
  db:
    image: 1000kit/h2
    environment:
      - MYSQL_ROOT_PASSWORD=P@ssw0rd
    ports:
      - 3306:3306